### ISSUE TITLE
Fails to install on windows

### ISSUE THREAD

**Issue by spuder** [alertlogic/al_agents#41]
I've appied the default recipe to a windows node running 2012 R2, Yet the installation always fails. private key redacted. 

```ruby
Recipe: al_agents::_windows
  * remote_file[al_agent-LATEST.msi] action create_if_missing
    - create new file C:\chef\cache/al_agent-LATEST.msi
    - update content in file C:\chef\cache/al_agent-LATEST.msi from none to 0d8fc0
    (new content is binary, diff output suppressed)
  * windows_package[al_agent-LATEST.msi] action install

    ================================================================================
    Error executing action `install` on resource 'windows_package[al_agent-LATEST.msi]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1603'
    ---- Begin output of msiexec /qn /i "c:\chef\cache\al_agent-latest.msi"  /quiet prov_key=xxxxxxxxxxxxx prov_only=host sensor_host=10.254.90.220 sensor_port=80 ----
    STDOUT:
    STDERR:
    ---- End output of msiexec /qn /i "c:\chef\cache\al_agent-latest.msi"  /quiet prov_key=xxxxxxxxxxxxx prov_only=host sensor_host=10.254.90.220 sensor_port=80 ----
    Ran msiexec /qn /i "c:\chef\cache\al_agent-latest.msi"  /quiet prov_key=xxxxxxxxxxxxx prov_only=host sensor_host=10.254.90.220 sensor_port=80 returned 1603

    Resource Declaration:
    ---------------------
    # In C:/chef/cache/cookbooks/al_agents/recipes/_windows.rb

     16: package basename do
     17:   source cached_package
     18:   action :install
     19:   options windows_options
     20:   not_if windows_install_guard
     21: end
     22:

    Compiled Resource:
    ------------------
    # Declared in C:/chef/cache/cookbooks/al_agents/recipes/_windows.rb:16:in `from_file'

    windows_package("al_agent-LATEST.msi") do
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      options "/quiet prov_key=xxxxxxxxxxxxx prov_only=host sensor_host=10.254.90.220 sensor_port=80"
      package_name "al_agent-LATEST.msi"
      source "c:\\chef\\cache\\al_agent-latest.msi"
      version "2.1.2.0"
      timeout 600
      returns [0]
      declared_type :package
      cookbook_name "al_agents"
      recipe_name "_windows"
      not_if "C:\Program Files (x86)\Common Files\AlertLogic\host_key.pem"
    end
```

I can't tell why the msi doesn't work. Can you provide any assistance to get this cookbook working?

**Update**

Looks like running the following MSI command manually works. (Removed the provision only flag)

msiexec /i "c:\chef\cache\al_agent-latest.msi" prov_key=xxxxxxx sensor_host=vaporator.alertlogic.com sensor_port=443

**Comment by jearly** [comment]
@spuder According to Microsoft exit code 1603 can be any of the following:

###### Symptoms:
When you try to install a Microsoft Windows Installer package, you may receive the following error message:
Error 1603: A fatal error occurred during installation.
If you click OK in the message box, the installation rolls back.

###### Cause:
You may receive this error message if any one of the following conditions is true:
The folder that you are trying to install the Windows Installer package to is encrypted.
The drive that contains the folder that you are trying to install the Windows Installer package to is accessed as a substitute drive.
The SYSTEM account does not have Full Control permissions on the folder that you are trying to install the Windows Installer package to. You notice the error message because the Windows Installer service uses the SYSTEM account to install software.

###### Resolution:
To resolve this problem, do any one of the following, depending on the cause of the problem:
Install the package to a folder that is not encrypted.
Use this method if you receive the error message because you try to install the Windows Installer package to a folder that is encrypted.
Install the package to a drive that is not accessed as a substitute drive.
Use this method if you receive the error message because the drive that contains the folder that you try to install the Windows Installer package to is accessed as a substitute drive.
Grant Full Control permissions to the SYSTEM account. (for Windows 2000 and Windows XP only)
Use this method if you receive the error message because the SYSTEM account does not have Full Control permissions on the folder that you try to install the Windows Installer package to. 

See reference link below for more detail from Microsoft on resolving this issue.

###### Reference: 
https://support.microsoft.com/en-us/kb/834484

**Comment by spuder** [comment]
Thanks, Figured it out. This is a bug in the cookbook that I've opened here: https://github.com/alertlogic/al_agents/issues/42

The work around is to set `for_imaging: false` and `for_autoscaling:false` in the role
